# Generated by Django 3.0.8 on 2020-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada', models.BooleanField(default=False)),
                ('descricao', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
