# Generated by Django 3.0.8 on 2020-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_agendamento', models.CharField(max_length=40)),
                ('data', models.DateField()),
                ('horainicio', models.TimeField()),
                ('horafinal', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
