# Generated by Django 3.0.8 on 2020-11-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='teste',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
