# Generated by Django 3.0.8 on 2020-10-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('mg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qnt_comprimidos', models.IntegerField()),
                ('intervalo', models.CharField(max_length=40)),
                ('horario_inicial', models.CharField(max_length=40)),
                ('horario_de_tomar', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Remedios',
            },
        ),
    ]
