# Generated by Django 3.0.8 on 2020-10-28 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remedio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedio',
            name='horario_de_tomar',
        ),
        migrations.AddField(
            model_name='remedio',
            name='dose',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedio',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
