# Generated by Django 3.0.8 on 2020-10-29 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remedio', '0002_auto_20201028_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedio',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='remedio',
            name='horario_inicial',
        ),
        migrations.RemoveField(
            model_name='remedio',
            name='intervalo',
        ),
        migrations.RemoveField(
            model_name='remedio',
            name='qnt_comprimidos',
        ),
        migrations.RemoveField(
            model_name='remedio',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_comprimidos', models.IntegerField()),
                ('intervalo', models.CharField(max_length=40)),
                ('horario_inicial', models.CharField(max_length=40)),
                ('dose', models.IntegerField()),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remedio.Remedio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recomendações',
            },
        ),
    ]
