# Generated by Django 3.0.8 on 2020-10-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0003_auto_20201029_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='mg',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
