# Generated by Django 3.0.8 on 2020-10-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0004_auto_20201029_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='horario_inicial',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='intervalo',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='horarios',
            field=models.ManyToManyField(to='remedio.Horario'),
        ),
    ]
