# Generated by Django 3.0.8 on 2020-10-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0005_auto_20201029_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='horarios',
            field=models.ManyToManyField(blank=True, null=True, to='remedio.Horario'),
        ),
    ]
