# Generated by Django 3.0.8 on 2020-10-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0008_remove_recomendacao_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='horarios',
            field=models.ManyToManyField(to='remedio.Horario'),
        ),
    ]
