# Generated by Django 3.0.8 on 2020-10-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0009_recomendacao_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='horarios',
            field=models.ManyToManyField(null=True, to='remedio.Horario'),
        ),
    ]
