# Generated by Django 3.0.8 on 2020-10-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0012_remove_recomendacao_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='horario_inicial',
            field=models.TimeField(),
        ),
    ]
