# Generated by Django 3.0.8 on 2020-11-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0013_auto_20201029_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='horario_inicial',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='qnt_comprimidos',
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='dias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='proximo_horario',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='quantidade_restante',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='quantidade_total_comprimidos',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='ultima_hora_que_tomou',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
    ]
