# Generated by Django 3.0.8 on 2020-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0014_auto_20201118_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='proximo_horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='quantidade_restante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='quantidade_total_comprimidos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
