# Generated by Django 3.0.8 on 2020-11-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0016_recomendacao_quantidade_tomada_comprimidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='quantidade_tomada_comprimidos',
            field=models.IntegerField(default=0),
        ),
    ]
