# Generated by Django 3.0.8 on 2020-11-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0018_auto_20201119_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='dose',
        ),
    ]
