# Generated by Django 3.0.8 on 2020-11-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0019_remove_recomendacao_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='ultima_hora_que_tomou',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
