# Generated by Django 3.0.8 on 2020-11-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0020_auto_20201119_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='proximo_horario',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
