# Generated by Django 3.0.8 on 2020-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=250)),
                ('dataAbertura', models.DateField(auto_now_add=True)),
                ('horarioAbertura', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chamados',
            },
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('status_impressora', models.CharField(choices=[('F', 'FUNCIONANDO'), ('D', 'DEFEITO'), ('R', 'REPARO')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Impressoras',
            },
        ),
    ]
