# Generated by Django 3.0.8 on 2020-10-23 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_impressora', models.CharField(choices=[('F', 'FUNCIONANDO'), ('D', 'DEFEITO'), ('R', 'REPARO')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Impressoras',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=250)),
                ('dataAbertura', models.DateField(auto_now_add=True)),
                ('horarioAbertura', models.TimeField(auto_now_add=True)),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.Impressora')),
            ],
            options={
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
