# Generated by Django 3.0.8 on 2020-11-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='nome',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
