# Generated by Django 3.0.8 on 2020-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_impressora_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='resposta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
