# Generated by Django 3.0.8 on 2020-11-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_impressora_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressora',
            name='resposta',
        ),
    ]
