# Generated by Django 3.0.8 on 2020-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(max_length=40)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nomeEvento', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
