# Generated by Django 3.0.8 on 2020-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_evento_quantidade_maxima_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='quantidade_maxima_pessoas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
